### ISSUE TITLE
Workers availability

### ISSUE THREAD

**Issue by MuyaoXi9271** [boecker-lab/sirius#81]
Hi expert,

The connection of "workers availability" sometimes works and sometimes does not work. The version I am currently using is version 5.5.7. And the setting of the network is that "Use Proxy Server" selects "NONE"

Do you have some suggestions on what should I do? Leave it fixing by itself or make some changes to the network setting

Bests,
Muyao

**Comment by mfleisch** [comment]
Hey Moyao,
thanks for reporting. We are aware of this issue and are working on a fix. 
So, for now  you can just wait until we identified the source of this issue.

We have deployed a possible fix today but since we are not able reproduce the problem we have to monitor and see if it happens again to verify if the fix is working.
 
Best
Markus

**Comment by marcus-ludwig** [comment]
HI Muyao, 

the issue seems to persist still. Do you encounter this frequently after submitting CSI:FingerID or CANOPUS jobs?
If so, it may be that your data is related to the issues of the workers.
In this case, it would be great if you could help us locate the issue.

Best,
Marcus

**Comment by MuyaoXi9271** [comment]
Hi Marcus,

I could still see the error at a random time. I am willing to help you to locate the issue. How can I help you? In my case, I put MS2 spectra related to many chemical compounds in one .mgf file and upload my file via "Import". It is fine at the beginning, and I receive the error dialogue when it is computing.


Bests,
Muyao

**Comment by marcus-ludwig** [comment]
Hi Muyao, 

would you be ok with sharing your data with us? So we can check if the issue is really related to your data?
You can contact us privately and send data (or download link) to the email address provided at the main page: https://github.com/boecker-lab/sirius

Best,
Marcus

**Comment by MuyaoXi9271** [comment]
Hi Marcus,

I do not have the right to share the data with you. I am so sorry about that. But in my personal feeling, it might not be the problem with my data, because I still receive the error message even though I do not run any job. 


Bests,
Muyao

**Comment by marcus-ludwig** [comment]
Hi Muyao,

Have you submitted the same data this morning and yesterday (about 14h and 20h ago)? If not, you are probably right and this is unrelated.

Best,
Marcus

**Comment by MuyaoXi9271** [comment]
Hi Marcus,

I did not submit any data this morning and yesterday.

Bests,
Muyao

**Comment by landerson23** [comment]
Hello,

I'm having a similar problem where the worker instances are consistently unavailable for FINGER_ID, CANOPUS, and COVTREE. I am also periodically given a failed connection to SIRIUS web service message, although that reconnects on its own fairly quickly. I installed the newest version of SIRIUS, but this problem persists. I'd appreciate any help you can offer!

**Comment by kaibioinfo** [comment]
Yes, the problem persists and Markus is currently on vacation ^^° We can just restart the workers whenever the problem occurs until Markus is back.

**Comment by Chao-Jui** [comment]
Hello all,

I also encountered a similar problem with Workers availability
the version I used was SIRIUS+CSI:FingerID GUI and CLI - Version 5.5.7 (2022-07-13) for Windows download from msi
the Use Proxy Server was also "NONE"
the problem I meet was that when I logged in, the connection check of workers availability was always failed even without upload a file. Also the connection to SIRIUS web service was sometimes connected and sometimes interrupt

The Worker information shown was  
Worker instances unavailable for 
FINGER_ID_POS, FINGER_ID_NEG, CANOPUS_POS,
CANOPUS_NEG, COVTREE_POS, COVTREE_NEG

Looking forward to your reply when you restart the workers 

Bests,
Chao-Jui

**Comment by landerson23** [comment]
Hi,

Do you mind restarting the workers again? Your quick fix worked great last time, but the workers are down again.

Any updates on when Markus will be back?

Thank you!

**Comment by kaibioinfo** [comment]
Hi, Markus is back and I think he solved the problem.

**Comment by mfleisch** [comment]
Yes should be fine again.
